#server:
#  port: 8761
#eureka:
#  client:
#    register-with-eureka: false #单机版建议设置为false，设置false的目的是防止自己注册自己，集群版采用默认的true
#    fetch-registry: false #单机版建议设置为false，设置false的目的是防止自己发现自己，集群版采用默认的true
## 服务认证
#spring:
#  application:
#    name: eureka-server # 应用名
#  security:
#    user:
#      name: admin #用户名
#      password: eureka  #密码


#eureka集群配置如下
spring:
  application:
    name: discovery-cluster #应用名
#  profiles:
#    active: discovery1


---
spring:
  profiles: discovery1   #注册中心1
  security:
   user:
     name: discovery1
     password: 123456
server:
  port: 8761
eureka:
  instance:
    hostname: discovery1
  client:
    serviceUrl:
      defaultZone: http://discovery2:123456@discovery2:8762/eureka,http://discovery3:123456@discovery3:8763/eureka
---
spring:
  profiles: discovery2  #注册中心2
  security:
   user:
     name: discovery2
     password: 123456
server:
  port: 8762
eureka:
  instance:
    hostname: discovery2
  client:
    serviceUrl:
      defaultZone: http://discovery1:123456@discovery1:8761/eureka,http://discovery3:123456@discovery3:8763/eureka
---
spring:
  profiles: discovery3  #注册中心3
  security:
   user:
     name: discovery3
     password: 123456
server:
  port: 8763
eureka:
  instance:
    hostname: discovery3
  client:
    serviceUrl:
      defaultZone: http://discovery1:123456@discovery1:8761/eureka,http://discovery2:123456@discovery2:8762/eureka