eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/  #eureka注册中心地址
      defaultZone: http://discovery1:123456@discovery1:8761/eureka,http://discovery2:123456@discovery2:8762/eureka,http://discovery3:123456@discovery3:8763/eureka  #服务器集群
spring:
  application:
    name: shang-usercenter-service
server:
  port: 8888 #应用名